# .graphclientrc.yml
sources:
  - name: ethereumPrimary
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/spark-lend-ethereum
  - name: gnosisPrimary
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/messari/spark-lend-gnosis
